// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt9ZoF4QwdRruKW3y5b4pvdtkHm5GQSVc',
    appId: '1:252164220322:web:8a193759996df89d317efb',
    messagingSenderId: '252164220322',
    projectId: 'mini-gpt-f5980',
    authDomain: 'mini-gpt-f5980.firebaseapp.com',
    storageBucket: 'mini-gpt-f5980.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJyOOIFbVNbjnMWI5b0-m870_EYIhpyFk',
    appId: '1:252164220322:android:6ad3bb685d55ddef317efb',
    messagingSenderId: '252164220322',
    projectId: 'mini-gpt-f5980',
    storageBucket: 'mini-gpt-f5980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2WKWLiFvyl3vcHpVI12P9BPwfBGMTnCk',
    appId: '1:252164220322:ios:28cfcee0ad6d0158317efb',
    messagingSenderId: '252164220322',
    projectId: 'mini-gpt-f5980',
    storageBucket: 'mini-gpt-f5980.firebasestorage.app',
    iosBundleId: 'com.example.gptMini',
  );

}